### ISSUE TITLE
Colors not working in descriptio 1.1 in ggassoc_crosstab

### ISSUE THREAD

**Issue by scouix** [nicolas-robette/descriptio#1]
Hi !

I love your package, but I can't make the "colors" option working. The pdf manual specifies that colors option is a vector. 
But, when I write :
`ggassoc_crosstab(data_global, mapping = ggplot2::aes(x=Canal, y=Acteur_cat), colors=c("green","red"))`

I get: 
`Error in ggassoc_crosstab(data_global, mapping = ggplot2::aes(x = Canal,  : 
  unused argument (colors = c("green", "red"))`

What do I do wrong ? 
Thank you !

**Comment by nicolas-robette** [comment]
Hi !
It's strange : I've tried to adapt the example in the documentation to your problem and it works like a charm.

`data(Movies)`
`ggassoc_crosstab(data=Movies, mapping=ggplot2::aes(Genre, Country), colors = c("red", "green"))`

Are you sure you have the last version of the package (which is actually the one on CRAN) ?

**Comment by scouix** [comment]
Hi !
Very strange indeed... I got this with your code :
```
ggassoc_crosstab(data=Movies, mapping=ggplot2::aes(Genre, Country), colors=c("red","green"))
Error in ggassoc_crosstab(data = Movies, mapping = ggplot2::aes(Genre,  : 
  could not find function "ggassoc_crosstab"
```
Descriptio package is coming from CRAN. Package version returns : 
```
> packageVersion("descriptio")
[1] ‘1.1’
```

I use Rstudio 2023.03.0

**Comment by nicolas-robette** [comment]
And if you restart R and execute the following code ?

```
library(descriptio)
library(ggplot2)
data(Movies)
ggassoc_crosstab(data=Movies, mapping=aes(Genre, Country), colors = c("red", "green"))
```

**Comment by scouix** [comment]
Hi !
Sorry for late responding. Executing your last code in a new file works like a charm...!
So the error is in my script !! 
I'll try to figure it out what going wrong and post it when I find the culprit !
Thank you and sorry for your time...!

Stanislas

**Comment by scouix** [comment]
When trying to figure out what's happening with my code, I found something very strange. 
When I re-run my old code and got a new error :
```
Computation failed in `stat_twocat()`
Caused by error in `stats::chisq.test()`:
! 'x' doit avoir au moins 2 éléments 
```

After many tries, I think I got something. I have exactly the same error if in put the Movies data in Excel and import it (as I do for my data). 
Executing this code shows the same error I get with my original code: 
```
library(readxl)
library(descriptio)
library(ggplot2)
data <- read_excel("Movies.xls")
ggassoc_crosstab(data, mapping=aes(Genre, Country))
```

`data` is a Tibble as shown by `class(data)`. I transformed it into a dataframe (with `data<-as.data.frame(data)`) ==> this changes nothing. [edit: I also tried with `read.csv(mov.csv)` which create a dataframe (not a tibble) but I got the same error...]
So I don't know why the error occur when the data comes from excel (or read.csv). In the same script, replacing data with Movies `ggassoc_crosstab(data=Movies, mapping=aes(Genre, Country))` works like a charm...!
Do you have any clue what's happening???

Thank you !

(PS : other function of the package works perfectly with data from excel, only the graphic functions show the error)

**EDIT : EUREKA ! I FOUND THE ISSUE !!
The issue is in read_excel function that doesn't convert categorical variables as Factors !! running `data$Variable <- as.factor(data$Variable)` for each categorical data fix the issue !!
read_csv got an option "stringsAsFactors=TRUE" that fixes also the issue
Now, colors are working fine !!**

**Comment by nicolas-robette** [comment]
I'm glad you finally fixed this issue !

Bests,
Nicolas
